FROM node:13-alpine

# Create and switch to /app
RUN mkdir /app
WORKDIR /app

# Install npm packages
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @vue/cli

COPY . /app

# Start the app
CMD ["npm", "run", "serve"]